services:
  ubuntu-poco:
    image: ubuntu-poco
    build: 
      context: .
      dockerfile: Dockerfile_poco
    command: /bin/true
  mariadb:
    image: mariadb_server
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: db_server
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
  chat:
    image: chat
    container_name: chat_service
    restart: always
    build:
      context: ./chat
      dockerfile: Dockerfile
    environment:
      DB_HOST: 192.168.100.173
      DB_PORT: 3306
      DB_LOGIN: user
      DB_PASSWORD: password
      DB_DATABASE: db
  wall:
    image: wall
    container_name: wall_service
    restart: always
    build:
      context: ./wall
      dockerfile: Dockerfile
    environment:
      DB_HOST: 192.168.100.173
      DB_PORT: 3306
      DB_LOGIN: user
      DB_PASSWORD: password
      DB_DATABASE: db
  user:
    image: user
    container_name: user_service
    restart: always
    build:
      context: ./user
      dockerfile: Dockerfile
    environment:
      DB_HOST: 192.168.100.173
      DB_PORT: 3306
      DB_LOGIN: user
      DB_PASSWORD: password
      DB_DATABASE: db
